# based on https://github.com/carderne/postmodern-python/blob/main/.github/workflows/pr.yml

name: pr

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:  # allow manual triggering of the workflow

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # changes:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: read
  #   outputs:
  #     python: ${{ steps.filter.outputs.python }}
  #   steps:
  #     - uses: dorny/paths-filter@v3
  #       id: filter
  #       with:
  #         filters: |
  #           python:
  #           - '**/*.py'
  #           - 'pyproject.toml'

  test-python:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        py: ['3.11', '3.12']
        # not today, windows-latest
        os: [ubuntu-latest, macos-latest]

    # needs: changes
    # if: needs.changes.outputs.python == 'true'
    steps:
    - uses: actions/checkout@v4
    - uses: eifinger/setup-rye@v4  # replaces setup-python
      id: setup-rye
      with:
        version: '0.39.0'
    - run: rye pin ${{ matrix.py }}
    - name: Sync
      shell: pwsh
      run: |
        rye sync
        if (git diff --stat requirements.lock) {
            Write-Output 'Rye lockfile not up-to-date'
            git diff requirements.lock
            exit 1
        }
    - run: rye fmt --check
    - run: rye lint
    - run: rye run check
    - run: rye run test
